[overlay]
	enabled = true
	#Range: 0.0 ~ 1.7976931348623157E308
	scale = 0.9

	[overlay.position]
		#Use negative values to position relative to the right/bottom of the screen
		#Range: > -2147483648
		x = 28
		#Range: > -2147483648
		y = 5

[effects]
	seasonal = true
