name = "LySMP"
author = "Sumire & Co."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e6a1d4df4740bb280bbf551b3df8fff021e9b3b19356a7e611b6cf199f11389"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.3"
