name = "LySMP"
author = "Sumire & Co."
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac63da9373a2efc978efc547a81daf8326e6cbcbe177b06340b573dff641c95a"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.3"
