name = "LySMP"
author = "Sumire & Co."
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af53db04c21912972bb9b11e84d19b08af58cbb699aa7afffbb07c1ebde96ff8"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.3"
