name = "LySMP"
author = "Sumire & Co."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9380f0ea47c565717a7a59db976e1dad1498b8d349adec1b618c9e3cd548848"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
