name = "LySMP"
author = "Sumire & Co."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ed08317cc450fffa073952775cd10f2e96f7801aed2b4f4730cdcbdeda70879"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
