name = "LySMP"
author = "Sumire & Co."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2918030ae0dd25740d37d626feec02c849e75879fce5a07f737ffd8bda9074b0"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
