name = "LySMP"
author = "Sumire & Co."
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ea34281a7b9e9a0b38e8bebbfdb8f3bf680c9903eb31ee1962baf8d9a2f17fc"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.3"
