name = "LySMP"
author = "Sumire & Co."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41c581c9526e74bb4b687f62ab876fc0dacb96c829916019a5aeb7774ae15fc1"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
