name = "LySMP"
author = "Sumire & Co."
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a64712bdab412d63890acce238e01dca6e48517108a346109135955f28f50121"

[versions]
minecraft = "1.20.1"
quilt = "0.28.0-beta.3"
