name = "LySMP"
author = "Sumire & Co."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc82025b02fff70e8b3e4ddf84916e4e99711e21a0357b726af79b1a15742c93"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
