name: Export Modpack
run-name: Exporting ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'Snapshot'}}.
on:
  push:
    tags:
      - 'v*.*.*'
    paths:
      - 'modpack/**'
      - '!modpack/packwiz*'
      - '!modpack/.packwizignore'
env:
  PACK_NAME: LySMP
jobs:
  versioning:
    name: Define version
    runs-on: ubuntu-latest
    outputs:
      version: ${{env.version}}
    env:
      version: ''
    steps:
      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo "version=${{github.ref_name}}" >> "$GITHUB_ENV"
      - if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: echo "version=build.${{github.run_number}}" >> "$GITHUB_ENV"

  export:
    name: Export Modpack
    runs-on: windows-latest
    needs:
      - versioning
    env:
      VERSION: ${{needs.versioning.outputs.version}}
    steps:
      - name: Checkout pack
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            modpack/**
          sparse-checkout-cone-mode: false
      - name: Export Build as .mrpack
        working-directory: modpack
        run: |
          ./packwiz.exe modrinth export --output ${{env.PACK_NAME}}-${{env.VERSION}}.mrpack
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.PACK_NAME}}-${{env.VERSION}}
          path: modpack/${{env.PACK_NAME}}-${{env.VERSION}}.mrpack
          if-no-files-found: error
          overwrite: true

  release:
    name: Make Releases
    runs-on: ubuntu-latest
    needs:
      - versioning
      - export
    permissions:
      contents: write
    env:
      VERSION: ${{needs.versioning.outputs.version}}
    steps:
      - uses: actions/checkout@v4

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{env.PACK_NAME}}-${{env.VERSION}}

      - name: GH Release Version
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2.0.8
        with:
          prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}
          make_latest: ${{ !( contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') ) }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: ${{env.PACK_NAME}}-${{env.VERSION}}.mrpack
          body: >
            To use the modpack, download the file `${{env.PACK_NAME}}-${{env.VERSION}}.mrpack` and import into
            your preferred launcher.
            
            note: curseforge does not support mrpacks.
            
            more information on what has changed since the last version can be found linked below:
            

      # =-=-=-=-=-=-=-=-=-=-= SETUP GIT TAGS =-=-=-=-=-=-=-=-=-=-=-=
      - name: Setup git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Tag as latest
        if: ${{ startsWith(github.ref, 'refs/tags/') && !( contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') ) }}
        run: git tag -f -a latest -m "Latest release version of the modpack"

      - name: Tag as stable
        if: ${{ startsWith(github.ref, 'refs/tags/') && !contains(github.ref_name, 'alpha') }}
        run: git tag -f -a stable -m "Latest stable version of the modpack"

      - name: Tag as snapshot
        run: git tag -f -a SNAPSHOT -m "Latest version of the modpack"

      - name: Push tags
        run: git push origin --tags --force

      # =-=-=-=-=-=-=-=-=-=-= SETUP NIGHTLY RELEASES =-=-=-=-=-=-=-=-=-=-=-=
      - name: Delete previous Snapshot release
        uses: s00d/delete-older-releases@0.2.1
        with:
          keep_latest: 0
          delete_tag_pattern: SNAPSHOT
          delete_type: prerelease
          delete_branch: ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: GH Release Snapshot
        uses: softprops/action-gh-release@v2.0.8
        with:
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/') || ( contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') )}}
          make_latest: false
          generate_release_notes: false
          fail_on_unmatched_files: true
          tag_name: SNAPSHOT
          files: ${{env.PACK_NAME}}-${{env.VERSION}}.mrpack
          body: >
            More information on this version is linked below:
            
            
            ${{ startsWith(github.ref, 'refs/tags/') && format('[{0}](https://github.com/LizzieSpace/LySMP/releases/tag/{0})', github.ref_name) || format('[{0}](https://github.com/LizzieSpace/LySMP/actions/runs/{1})',env.VERSION ,github.run_id)}}
            ${{ !(startsWith(github.ref, 'refs/tags/') && !contains(github.ref_name, 'alpha')) && "is unstable! Use it at your own risk." || '' }}
            

      - name: Delete previous Stable release
        uses: s00d/delete-older-releases@0.2.1
        with:
          keep_latest: 0
          delete_tag_pattern: stable
          delete_type: prerelease
          delete_branch: ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: GH Release Stable
        if: ${{ startsWith(github.ref, 'refs/tags/') && !contains(github.ref_name, 'alpha') }}
        uses: softprops/action-gh-release@v2.0.8
        with:
          prerelease: ${{ contains(github.ref_name, 'beta') }}
          make_latest: false
          generate_release_notes: false
          fail_on_unmatched_files: true
          tag_name: stable
          files: ${{env.PACK_NAME}}-${{env.VERSION}}.mrpack
          body: >
            More information on this version is linked below:


            ${{ format('[{0}](https://github.com/LizzieSpace/LySMP/releases/tag/{0})', github.ref_name) }}


      - name: Delete previous Latest release
        uses: s00d/delete-older-releases@0.2.1
        with:
          keep_latest: 0
          delete_tag_pattern: latest
          delete_type: release
          delete_branch: ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: GH Release Latest
        if: ${{ startsWith(github.ref, 'refs/tags/') && !( contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') ) }}
        uses: softprops/action-gh-release@v2.0.8
        with:
          prerelease: false
          make_latest: false
          generate_release_notes: false
          fail_on_unmatched_files: true
          tag_name: latest
          files: ${{env.PACK_NAME}}-${{env.VERSION}}.mrpack
          body: >
            More information on this version is linked below:
            
            
            ${{ format('[{0}](https://github.com/LizzieSpace/LySMP/releases/tag/{0})', github.ref_name) }}

      # =-=-=-=-=-=-=-=-=-=-= DELETE OUTDATED PRE-RELEASES =-=-=-=-=-=-=-=-=-=-=-=
      - name: Delete Older Beta Releases
        uses: s00d/delete-older-releases@0.2.1
        with:
          keep_latest: 3
          delete_tag_pattern: beta
          delete_type: prerelease
          delete_branch: ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Delete Older Alpha Releases
        uses: s00d/delete-older-releases@0.2.1
        with:
          keep_latest: 3
          delete_tag_pattern: alpha
          delete_type: prerelease
          delete_branch: ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ github.token }}

